config/routes.rb
Rails.application.routes.draw do
  root      'flights#index'
  resources :flights,   only: [:index]
  post      '/flights', to: 'flights#index'   
  resources :bookings,  only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: 'from_code_id', class_name: 'Flight'
  has_many :arriving_flights,  foreign_key: 'to_code_id',   class_name: 'Flight'

  validates :code, presence: true, length: { is: 3 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many   :passengers, inverse_of: :booking
  accepts_nested_attributes_for :passengers, 
    reject_if: lambda { |attributes| attributes[:name].blank? || attributes[:email].blank? }

  validates :flight_id, presence: true
  validates :num_of_tickets, numericality: { only_integer: true, greater: 0, 
                                             less_than: 5 }
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to  :departure, class_name: 'Airport'
  belongs_to  :arrival,   class_name: 'Airport'
  has_many    :bookings

  validates :departure_id,    presence: true
  validates :arrival_id,      presence: true
  validates :departure_date,  presence: true
  validates :duration,        presence: true

  def self.departure_dates
    Flight.select(:departure_date).distinct
          .where(['departure_date >= ?', DateTime.current])
          .order(:departure_date)
  end

  def self.upcoming
    Flight.where('departure_date > ?', DateTime.current)
  end

  def self.search(departure_id, arrival_id ,departure_date)
    Flight.where('departure_id = ? AND arrival_id = ? AND departure_date > ? ',
                  departure_id, arrival_id, departure_date)
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking, inverse_of: :passengers

  before_save :downcase_email

  validates_presence_of :booking
  validates :name,       presence: true, length: { in: 2..60 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email,      presence: true, length: { maximum: 50 },
                         format: { with: VALID_EMAIL_REGEX },
                         uniqueness: { case_sensitive: false }
                         
  private

    def downcase_email
      email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  include FlightsHelper

  def new
    pick_flight_validation
    @flight         = Flight.find_by(id: params[:flight_id])
    @num_of_tickets = params[:num_of_tickets].to_i
    @booking        = Booking.new
    @num_of_tickets.times { @booking.passengers.build }
  end

  def create
    flight  = Flight.find_by(id: params[:booking][:flight_id])
    @booking = Booking.new(booking_params)

    if @booking.save
      send_thank_you_email(@booking.passengers)
      flash[:success] = 'Successfully booked a flight'
      redirect_to @booking
    else
      flash[:danger] = "Something went wrong please check your input if it's valid"
      redirect_to root_path
    end
  end

  def show
    @booking = Booking.find_by(id: params[:id])
    unless @booking
      flash[:danger] = 'Booking not found'
      redirect_to root_url
    end
    @flight = @booking.flight
    @num_of_tickets = @booking.num_of_tickets
  end

  private

    def booking_params
      params.require(:booking).permit(:flight_id, :num_of_tickets,
                                      passengers_attributes: [:id, :name, :email])
    end

    def send_thank_you_email(passengers)
      passengers.each do |passenger|
        PassengerMailer.with(passenger: passenger).thank_you_email.deliver_now
      end
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.upcoming.paginate(page: params[:page])
    if params[:search]
      @departure = params[:search][:departure_id]
      @arrival = params[:search][:arrival_id]
      @num_of_tickets = params[:search][:num_of_tickets]
      @departure_date = params[:search][:departure_date]
      @flights = Flight.search(@departure, @arrival, @departure_date)
                       .paginate(page: params[:page])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Odin Flight Booker'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  def pick_flight_validation
    if (params[:flight_id].nil? || params[:num_of_tickets].nil?)
      if params[:flight_id].nil?
        flash[:danger] = 'Please pick a flight first'
      elsif params[:num_of_tickets].nil?
        flash[:danger] = 'Please specify the number of tickets'
      end
      redirect_to root_path
      return
    end
  end
end

app/views/bookings/_booking.html.erb
<div class="card">
  <div class="card-header">
    <h1>Booking Information</h1>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><b>Flight #:</b> <%= @flight.id %></li>
    <li class="list-group-item"><b>Airport departure:</b> <%= @flight.departure.code %></li>
    <li class="list-group-item"><b>Arrival departure:</b> <%= @flight.arrival.code %></li>
    <li class="list-group-item">
    <b><%= 'Ticket'.pluralize(1) %>:</b> <%= @num_of_tickets %>
    </li>
  </ul>
</div>

app/views/bookings/_form.html.erb
<%= form_with model: @booking do |f| %>
  <%= f.hidden_field :flight_id, value: @flight.id %>
  <%= f.hidden_field :num_of_tickets, value: @num_of_tickets %>
  <% @booking.passengers.each_with_index do |passenger, i| %>
    <%= f.fields_for :passengers, passenger do |passenger_form| %>
      <p class="h3"><%= (i+1).ordinalize %> passenger</p>
      <div class="form-group">
        <%= passenger_form.label :name %>
        <%= passenger_form.text_field :name, class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= passenger_form.label :email %>
        <%= passenger_form.email_field :email, class: 'form-control', required: true %>
      </div>
    <% end %>
  <% end %>
  <%= f.submit 'Book', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/bookings/_passengers.html.erb
<div class="card">
  <div class="card-header">
    <h2>Passengers</h2>
  </div>
  <ul class="list-group list-group-flush">
    <% @booking.passengers.each do |passenger| %>
      <li class="list-group-item">
        <b>Name:</b> <%= passenger.name %> <br>
        <b>Email:</b> <%= passenger.email %>
      </li>
    <% end %>
  </ul>
</div>

app/views/bookings/show.html.erb
<div class="row justify-content-center">
  <div class="col-md-8">
    <%= render 'booking' %>
    <%= render 'passengers' %>
  </div>
</div>

app/views/flights/_flight.html.erb
<tr>
  <% if num_of_tickets %>
    <td><%= radio_button_tag :flight_id, flight.id %></td>
  <% end %>
  <th scope="row"><%= flight.id %></th>
  <td><%= label_tag "flight_id_#{flight.id}", flight.departure.code %></td>
  <td><%= label_tag "flight_id_#{flight.id}", flight.arrival.code %></td>
  <td><%= label_tag "flight_id_#{flight.id}", flight.departure_date %></td>
  <td><%= label_tag "flight_id_#{flight.id}", "#{flight.duration.round(2)} hours" %></td>
</tr>

app/views/flights/_flights.html.erb
<%= form_with local: true, url: new_booking_path, method: 'get' do %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% if @num_of_tickets %>
          <th scope="col">Select</th>
        <% end %>
        <th scope="col">#</th>
        <th scope="col">Airport Departure</th>
        <th scope="col">Airport Arrival</th>
        <th scope="col">Departure Date</th>
        <th scope="col">Flight Duration</th>
      </tr>
    </thead>
    <tbody>
      <%= render @flights, num_of_tickets: @num_of_tickets %>
    </tbody>
  </table>

  <%= hidden_field_tag 'num_of_tickets', @num_of_tickets %>

  <% if @flights.any? %>
    <%= will_paginate @events, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    <% if @num_of_tickets %>
      <%= submit_tag 'Pick Flight', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/flights/_search_form.html.erb
<%= form_with scope: 'search', local: true, url: flights_path, method: 'get' do |f| %>
  <div class="form-group">
    <%= f.label :departure, 'Airport departure' %>
    <%= f.collection_select :departure_id, Airport.all, :id, :code,
          { selected: @departure }, class: 'form-control custom-select'  %>
  </div>
  
  <div class="form-group">
    <%= f.label :arrival, 'Airport arrival' %>
    <%= f.collection_select :arrival_id, Airport.all, :id, :code, 
        { selected: @arrival }, class: 'form-control custom-select' %>
  </div>

  <div class="form-group">
    <%= f.label :num_of_tickets, 'Number of tickets' %>
    <%= f.select :num_of_tickets, [1, 2, 3, 4], 
        { selected: @num_of_tickets }, class: 'form-control custom-select' %>
  </div>

  <div class="form-group">
    <%= f.label :departure_date %>
    <%= f.select :departure_date, options_from_collection_for_select(Flight.departure_dates, 
          :departure_date, :departure_date, selected: @departure_date), {}, 
          class: 'form-control custom-select' %>
  </div>
  <%= f.submit 'Search', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/flights/index.html.erb
<div class="row justify-content-center">
  <div class="col-md-6 mb-4">
    <h2 class="text-center">Book or Search Flights</h2>
    <%= render 'search_form' %>
  </div>
  <div class="col-md-10">
    <h2 class="text-center mb-4">
      <% if @num_of_tickets %>
        Flights based on your search (<%= @flights.count %>)
      <% else %>
        Flights (<%= @flights.count %>)
      <% end %>
    </h2>
    <%= render 'flights' %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
  <%= link_to 'Odin Flight Booker', root_path, class: 'navbar-brand' %>
  <div class="collapge navbar-collapse">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item"><%= link_to 'Flights', root_path, class: 'nav-link' %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_rails_default_head_tags.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default_head_tags' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </main>
  </body>
</html>